// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Cactus_Classical_Serif } from "next/font/google";
// import "./globals.css";
// import { I18nProvider } from "./providers";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const cactusSerif = Cactus_Classical_Serif({
//   variable: "--font-cactus-serif",
//   subsets: ["latin"],
//   weight: "400",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
//         <link
//           href="https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@100;200;300;400;500;600;700;800;900&family=Cairo:wght@200;300;400;500;600;700;800;900&family=Amiri:ital,wght@0,400;0,700;1,400;1,700&family=Tajawal:wght@200;300;400;500;700;800;900&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${cactusSerif.variable} antialiased w-full overflow-x-hidden bg-black`}
//         suppressHydrationWarning
//       >
//         <Navbar/>
//         <I18nProvider>{children}</I18nProvider>
//         <Footer/>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Cactus_Classical_Serif } from "next/font/google";
// import "./globals.css";

// import { I18nProvider } from "./providers";
// import { CurrencyProvider } from "@/contexts/CurrencyContext"; // 👈 IMPORT THIS
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const cactusSerif = Cactus_Classical_Serif({
//   variable: "--font-cactus-serif",
//   subsets: ["latin"],
//   weight: "400",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         <meta
//           name="viewport"
//           content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
//         />
//         <link
//           href="https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@100;200;300;400;500;600;700;800;900&family=Cairo:wght@200;300;400;500;600;700;800;900&family=Amiri:ital,wght@0,400;0,700;1,400;1,700&family=Tajawal:wght@200;300;400;500;700;800;900&display=swap"
//           rel="stylesheet"
//         />
//       </head>

//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${cactusSerif.variable} antialiased w-full overflow-x-hidden bg-black`}
//         suppressHydrationWarning
//       >
//         {/* ✅ Providers must wrap Navbar */}
//         <I18nProvider>
//           <CurrencyProvider>
//             <Navbar />
//             {children}
//             <Footer />
//           </CurrencyProvider>
//         </I18nProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono, Cactus_Classical_Serif } from "next/font/google";
import "./globals.css";

import { I18nProvider } from "./providers";
import { CurrencyProvider } from "@/contexts/CurrencyContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cactusSerif = Cactus_Classical_Serif({
  variable: "--font-cactus-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Luvana Paris",
  description: "Luxury Shopping Experience",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@100;200;300;400;500;600;700;800;900&family=Cairo:wght@200;300;400;500;600;700;800;900&family=Amiri:ital,wght@0,400;0,700;1,400;1,700&family=Tajawal:wght@200;300;400;500;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cactusSerif.variable} antialiased w-full overflow-x-hidden bg-black`}
        suppressHydrationWarning
      >
        <I18nProvider>
          <CurrencyProvider>
            <Navbar />
            {children}
            <Footer />
          </CurrencyProvider>
        </I18nProvider>
      </body>
    </html>
  );
}